### ISSUE TITLE
Why z3 in /train/wgan_... needed?

### ISSUE THREAD

**Issue by leigaoyi** [jiamings/markov-chain-gan#2]
Hello, I'm surprised by so many tricks are used in this project. Maybe the project name shall add WGAN-GP.
Now I read the article twice and the code in this project, but I don't get the point why we **sample from noise z** and do twice sample (from z) to **calculate z1 and z3**, by step b and step m. 
I still have to learn more about the rnn part, just too many knowledge in such short code!
Thanks if you can help, and I don't mind you answer me in Chinese. 谢谢！

**Comment by jiamings** [comment]
WGAN+GP is pretty standard atm, so it would be natural to think of this "trick" when you do it.

The reason behind using 2 z's is to reduce the error introduced by having generated z not match the true z in b steps, but if you don't add that it should still be fine.
